language: node_js
node_js:
  - '5'
  - '4'

# (by default, Travis will run "yarn test" script when the language is node_js)

# deploy is run after "yarn test"
deploy:
  # keep the build we just made with "yarn test" (dist/)
  skip_cleanup: true

  # define the script to use for deployment
  provider: script
  script: ./scripts/deploy.sh

  # only run on one version of node (v5 here)
  on:
    branch: dev # ⚠️ OR SRC IF YOU USE USERNAME.GITHUB.IO
    node: '5'
