language: node_js
node_js:
  - '5'
  - '4'
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  'on':
    branch: dev
    node: '5'
env:
  global:
    - secure: >-
        ZuuxuZ1IAWcpYKEqNu6QKLjipF+R+Lpp7MhCWJKbDW3Mh+Qcurwq9aQjsOFJkWwM0BQROvsgG5DqLbLLEbCWmOgvSwfrgacEOVEHY3moK3wyC5iBSeOdIhGauEPMSlnbiSosmpnwMlbAfOV6CorxaC9/k3euqXkSb3cn3rZze0WrOzdIYEWOpGD56OOesWblDS5mZWk0aY6ycmbXqR3EeuZ0L2TG+NCg//cUZwcprJwMnUNEKc+t78brn6mAFKUTirntRheVPfrFPdsOTKtZ36vgxdw9o7GVU3D/Q0BZMii+YjT4JeFlJTVu5JpmqByAJ7veV5cmHh9GESsgcCYDEyWGZ4rxlzSgNaxP/u2eFgmSHxX2w534xg/hvqujWON7B+PiRjKEYtnxeb1aQcd4U1A0HNDh0f+FRgsom4UzG8j1WFx/eerdr0XAAu/vRFRw6iXdcG3ATBysGuXdzWIrD9udgl8mKEVyn8HsCRP5tRFa3zPMvQrRLfyek/N8bw62Vr0R0hdte0r8wA716yinaPTCbi0+vRLQiAfkVfa2rlFtR5PfVVzyGHntmshomt4YPwC0eVOqLM52jWC+rJFLpgiUJeAZlO8RDPiQh/9TSmNHvP7vnmhdrhp53fRQMGWsYj0GqDsGEOpjpBP3qeizroYpzP0OEfkJ9utQCaZdfz4=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/wwrpgroup/wwrpgroup.github.io.git
